default: &default
   adapter: postgresql
   encoding: unicode
   username: rubyuser
   password: admin
  
development:
   adapter: postgresql
   encoding: unicode
   database: library_development
   host: localhost
   pool: 5
   username: rubyuser
   password: admin

test:
   adapter: postgresql
   encoding: unicode
   database: library_test
   host: localhost
   pool: 5
   username: rubyuser
   password: admin
 
production:
   adapter: postgresql
   encoding: unicode
   database: library_production
   host: localhost
   pool: 5
   username: rubyuser
   password: admin